name:                logicFormula
version:             0.1.0.0
github:              "Jujules94/logicFormula"
license:             BSD3
author:              "Julien Bessodes"
maintainer:          "jbessode@etud.u-pem.fr"
copyright:           "CC"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Unknown

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Jujules94/logicFormula#readme>

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src
  exposed-modules:
    - Data.Logic.Fml
    - Data.Logic.Fml.Some
    - Data.Logic.Fml.Combinator
    - Data.Logic.Var
    - Data.Logic.Var.Some

executables:
  logicFormula-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - logicFormula

tests:
  logicFormula-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - logicFormula
